# pull node.js docker image
FROM node:14.15.4
#create a app directory to mount image
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install  --only=production
COPY . .
EXPOSE 9093
CMD ["npm","start"]